ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
  hosts:
    - suttyread.link
  tls:
    - secretName: mailu-tls
      hosts:
        - suttyread.link
mailu:
  domain: suttyread.link
  hostnames: mail.suttyread.link
  passwordScheme: SHA512-CRYPT
  secretKey: uRUYO6BszLap3cYPIhqnHAxp--0M5SuOK0-hWU5Y7Us
  postmaster: admin
  webdav: enabled
