apiVersion: v1
kind: Namespace
metadata:
  name: authelia

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-pvc
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
        - name: authelia
          image: authelia/authelia:4.37
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: config
              mountPath: /etc/authelia
            - name: storage
              mountPath: /var/lib/authelia
      volumes:
        - name: config
          configMap:
            name: authelia-config
        - name: storage
          persistentVolumeClaim:
            claimName: authelia-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      name: authelia
  selector:
    app: authelia

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: authelia
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
    - host: authelia.sutty.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia
                port:
                  number: 9091
  tls:
    - hosts:
        - authelia.sutty.shop
      secretName: authelia-tls

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  configuration.yml: |
    host: 0.0.0.0
    port: 9091
    log_level: info
    jwt_secret: your_jwt_secret
    default_redirection_url: https://authelia.sutty.shop

    authentication_backend:
      disable_reset_password: false
      refresh_interval: 5m
      ldap:
        url: ldap://authelia.sutty.shop
        skip_verify: false
        base_dn: dc=sutty,dc=shop
        additional_users_dn: ou=users
        users_filter: (&({username_attribute}={input})(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (&(member={dn})(objectClass=groupOfNames))
        group_name_attribute: cn
        mail_attribute: mail
        user: cn=admin,dc=sutty,dc=shop
        password: your_ldap_admin_password

    access_control:
      default_policy: deny
      rules:
        - domain: sutty.shop
          policy: one_factor

    session:
      name: authelia_session
      secret: your_session_secret
      expiration: 1h
      inactivity: 5m
      domain: sutty.shop
    
    regulation:
      max_retries: 3
      find_time: 2m
      ban_time: 5m
    
    storage:
      local:
        path: /var/lib/authelia/db.sqlite3
    
    notifier:
      filesystem:
        filename: /var/lib/authelia/notification.txt
    
