apiVersion: batch/v1
kind: Job
metadata:
  name: install-cert-manager-crds
spec:
  template:
    spec:
      containers:
        - name: kubectl-apply
          image: bitnami/kubectl
          command: ["kubectl", "apply", "-f", "https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.crds.yaml"]
      restartPolicy: Never
  backoffLimit: 4
