#kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Сервер URL для стейджингу Let's Encrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ryaremenko99@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: traefik

#EOF