apiVersion: v1
kind: Namespace
metadata:
  name: ldap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:latest
          ports:
            - containerPort: 389
          env:
            - name: LDAP_ORGANISATION
              value: "suttyread"
            - name: LDAP_DOMAIN
              value: "ldap.suttyread.link"
            - name: LDAP_ADMIN_PASSWORD
              value: "ldappassword"
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: ldap-data-pvc
        - name: ldap-config
          persistentVolumeClaim:
            claimName: ldap-config-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: ldap
spec:
  type: LoadBalancer
  ports:
    - port: 10389
      targetPort: 389
  selector:
    app: openldap

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data-pvc
  namespace: ldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-config-pvc
  namespace: ldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
