apiVersion: v1
kind: Namespace
metadata:
  name: ldap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:latest
          ports:
            - containerPort: 389
          env:
            - name: LDAP_ORGANISATION
              value: "suttyread"
            - name: LDAP_DOMAIN
              value: "ldap.suttyread.link"
            - name: LDAP_ADMIN_PASSWORD
              value: "adminpassword"

---

apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: ldap
spec:
  ports:
    - port: 389
      protocol: TCP
      targetPort: 389
  selector:
    app: openldap

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openldap-ingress
  namespace: ldap
spec:
  rules:
    - host: ldap.suttyread.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openldap
                port:
                  number: 389
