apiVersion: v1
kind: Namespace
metadata:
  name: mailcow

---

apiVersion: v1
kind: Service
metadata:
  name: mailcow
  namespace: mailcow
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: mailcow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailcow
  namespace: mailcow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailcow
  template:
    metadata:
      labels:
        app: mailcow
    spec:
      containers:
        - name: mailcow
          image: mailcow/dockerized:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: MAILCOW_HOSTNAME
              value: "sutty.shop"
            - name: DBNAME
              value: "mailcow"
            - name: DBUSER
              value: "user"
            - name: DBPASS
              value: "password"
          volumeMounts:
            - name: mailcow-vol
              mountPath: /opt/mailcow
      volumes:
        - name: mailcow-vol
          persistentVolumeClaim:
            claimName: mailcow-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailcow-pvc
  namespace: mailcow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
