DATABASE_PASSWORD: GPXrHJdsjMb#Vvu4
FULLTEXTSEARCH_PASSWORD: 8avRFfp^BsZqRKgP
NC_DOMAIN: sutty.shop
NEXTCLOUD_PASSWORD: fSkyGjx%WsxNnDfn
ONLYOFFICE_SECRET: kNunxNy7y%27J%HZ
RECORDING_SECRET: ZNPTrKGG)fqp5pKs
REDIS_PASSWORD: Ipv)nSDgUra9p+3E
SIGNALING_SECRET: W8N%rSq*vk4FFeUx
TALK_INTERNAL_SECRET: ga+k77bhb7hT!xKh
TIMEZONE: Europe/Berlin
TURN_SECRET: pzT!j57Ij&CpWnmA

CLAMAV_ENABLED: "no"
COLLABORA_ENABLED: "no"
FULLTEXTSEARCH_ENABLED: "no"
IMAGINARY_ENABLED: "no"
ONLYOFFICE_ENABLED: "yes"
TALK_ENABLED: "yes"
TALK_RECORDING_ENABLED: "yes"

APACHE_MAX_SIZE: "10737418240"
APACHE_PORT: 30211
COLLABORA_DICTIONARIES: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru
COLLABORA_SECCOMP_POLICY: --o:security.seccomp=true
INSTALL_LATEST_MAJOR: no
NEXTCLOUD_ADDITIONAL_APKS:
NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS:
NEXTCLOUD_MAX_TIME: 3600
NEXTCLOUD_MEMORY_LIMIT: 512M
NEXTCLOUD_STARTUP_APPS: deck twofactor_totp tasks calendar contacts notes
NEXTCLOUD_TRUSTED_CACERTS_DIR:
NEXTCLOUD_UPLOAD_LIMIT: 10G
REMOVE_DISABLED_APPS: yes
TALK_PORT: 30212
UPDATE_NEXTCLOUD_APPS: no
NAMESPACE: nextcloud

STORAGE_CLASS:
APACHE_STORAGE_SIZE: 1Gi
CLAMAV_STORAGE_SIZE: 1Gi
DATABASE_STORAGE_SIZE: 1Gi
DATABASE_DUMP_STORAGE_SIZE: 1Gi
ELASTICSEARCH_STORAGE_SIZE: 1Gi
NEXTCLOUD_STORAGE_SIZE: 5Gi
NEXTCLOUD_DATA_STORAGE_SIZE: 5Gi
NEXTCLOUD_TRUSTED_CACERTS_STORAGE_SIZE: 1Gi
ONLYOFFICE_STORAGE_SIZE: 1Gi
REDIS_STORAGE_SIZE: 1Gi