apiVersion: v1
kind: Namespace
metadata:
  name: ldap

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
  namespace: ldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: bitnami/openldap:latest
          ports:
            - containerPort: 1389
            - containerPort: 1636
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              value: "adminpassword"
            - name: LDAP_USERS
              value: "user1,user2"
            - name: LDAP_PASSWORDS
              value: "password1,password2"
            - name: LDAP_ORGANISATION
              value: "suttyshop"
            - name: LDAP_DOMAIN
              value: "ldap.sutty.shop"
          volumeMounts:
            - name: ldap-data
              mountPath: /bitnami/openldap
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: openldap-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: ldap
spec:
  type: ClusterIP
  ports:
    - port: 1389
      targetPort: 1389
      name: ldap
    - port: 1636
      targetPort: 1636
      name: ldaps
  selector:
    app: openldap

---

apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: web
  selector:
    app: phpldapadmin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: openldap.ldap
