apiVersion: v1
kind: Namespace
metadata:
  name: shlink

---
apiVersion: v1
kind: Service
metadata:
  name: shlink
  namespace: shlink
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31080
  selector:
    app: shlink

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink
  namespace: shlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink
  template:
    metadata:
      labels:
        app: shlink
    spec:
      containers:
        - name: shlink
          image: shlinkio/shlink:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_DRIVER
              value: "mysql"
            - name: DB_NAME
              value: "shlink"
            - name: DB_USER
              value: "shlink"
            - name: DB_PASSWORD
              value: "your-db-password"
            - name: DB_HOST
              value: "shlink-db"

---
apiVersion: v1
kind: Service
metadata:
  name: shlink-db
  namespace: shlink
spec:
  ports:
    - port: 3306
  selector:
    app: shlink-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-db
  namespace: shlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink-db
  template:
    metadata:
      labels:
        app: shlink-db
    spec:
      containers:
        - name: shlink-db
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "shlink"
            - name: MYSQL_USER
              value: "shlink"
            - name: MYSQL_PASSWORD
              value: "your-db-password"
            - name: MYSQL_ROOT_PASSWORD
              value: "your-root-password"
          volumeMounts:
            - name: shlink-db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: shlink-db-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: shlink-web-client
  namespace: shlink
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31081
  selector:
    app: shlink-web-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-web-client
  namespace: shlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink-web-client
  template:
    metadata:
      labels:
        app: shlink-web-client
    spec:
      containers:
        - name: shlink-web-client
          image: shlinkio/shlink-web-client:latest
          ports:
            - containerPort: 80
