apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.toml: |
    [entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

    [certificatesResolvers.myresolver.acme]
    email = "ryaremenko99@gmail.com"
    storage = "acme.json"
    [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "http"
    [certificatesResolvers.myresolver.acme.staging]
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
